//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
=======
//     Runtime Version:4.0.30319.42000
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace JsonArchitect {
=======
namespace JsonConverter {
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
<<<<<<< HEAD
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonArchitect.TextResources", typeof(TextResources).Assembly);
=======
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonConverter.TextResources", typeof(TextResources).Assembly);
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllOptional.
        /// </summary>
        internal static string allOptional {
            get {
                return ResourceManager.GetString("allOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string baseName {
            get {
                return ResourceManager.GetString("baseName", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to DetailedErrors.
        /// </summary>
        internal static string detailedErrors {
            get {
                return ResourceManager.GetString("detailedErrors", resourceCulture);
=======
        ///   Looks up a localized string similar to JSONContents.
        /// </summary>
        internal static string jsonContents {
            get {
                return ResourceManager.GetString("jsonContents", resourceCulture);
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to The selected language is not supported.
        /// </summary>
        internal static string LangNotSupported {
            get {
                return ResourceManager.GetString("LangNotSupported", resourceCulture);
=======
        ///   Looks up a localized string similar to JSONOutput.
        /// </summary>
        internal static string jsonOutput {
            get {
                return ResourceManager.GetString("jsonOutput", resourceCulture);
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootName.
        /// </summary>
        internal static string rootName {
            get {
                return ResourceManager.GetString("rootName", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
=======
        ///   Looks up a localized string similar to SelectedLang.
        /// </summary>
        internal static string selectedLang {
            get {
                return ResourceManager.GetString("selectedLang", resourceCulture);
            }
        }
        
        /// <summary>
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
        ///   Looks up a localized string similar to SuggestCorrs.
        /// </summary>
        internal static string suggestCorrs {
            get {
                return ResourceManager.GetString("suggestCorrs", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 1.1.0.
=======
        ///   Looks up a localized string similar to ThemeIndex.
        /// </summary>
        internal static string themeIndex {
            get {
                return ResourceManager.GetString("themeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateMsgs.
        /// </summary>
        internal static string validateMsgs {
            get {
                return ResourceManager.GetString("validateMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.9.1.
>>>>>>> 77352be7aa5a4294ded88c5feb1fe2f71acb70fc
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
